### ISSUE TITLE
Can't run project from withing Visual Studio with Godot 3.3.4

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-csharp-visualstudio#21] opened 2021-11-11 23:22 UTC
**OS/device including version:**
Windows 10 Pro 10.0.19043 Build 19043

**Issue description:**
I followed the documentation to set up Godot with visual studio but received error message when I try to run/debug my project from within the Visual Studio editor.  I posted about this on the Godot forums, and someone responded with a video describing the problem and showing a work around that involved manually rewriting the project file.  The Godot C# VisualStudio plugin should be updated to reflect the latest versions of Godot and VisualStudio so that solutions can be created that do not involve this amount of manual editing:

https://godotforums.org/discussion/27974/error-when-trying-to-run-project-from-within-visual-studio/p1?new=1

**Screenshots of issue:**

**Comment by cybereality** [comment] 2021-11-12 18:43
This also happens on Windows 11, latest Godot version 3.4 and Visual Studio 2019. More info here:
https://github.com/godotengine/godot/issues/54901

**Comment by neikeq** [comment] 2021-11-13 20:39
Closing as duplicate of #10.

We're stuck with this issue since we upgraded to Sdk style project files. There's poor documentation about extending Visual Studio for the new Sdk style projects. I tried these [official examples](https://github.com/microsoft/VSProjectSystem/tree/master/samples) as well without success. I don't know if what we need is supported at all or just poorly documented.

**Closed by neikeq** 2021-11-13 20:39 UTC
Labels: bug
